name: 发送逛街通知邮件
on:
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.QQ_EMAIL }}
          password: ${{ secrets.QQ_AUTH_CODE }}
          subject: 周末去逛街
          body: |
            你和小红说一下
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.QQ_EMAIL }}
          secure: true  # 👈 就是加了这一行，修复 503 错误！
